### ISSUE TITLE
Handling duplicates in triangulation

### ISSUE THREAD

**Issue by shriv** [schochastics/edgebundle#11]
I have been trying to plot international trade flows from Aotearoa, New Zealand. I have ensured that there are no duplicates in nodes or edges but I still get the following error. 
```r
 Error in interp::tri.mesh(xymesh[, 1], xymesh[, 2]) : 
  duplicate data points 
```
In the end, I had to make the following change to `tnss_tree()` for the error to go away. 
```{r}
  #triangulate points
  tria <- interp::tri.mesh(xymesh[,1],xymesh[,2])
  tria <- interp::tri.mesh(xymesh[,1],xymesh[,2], duplicate = "remove")
```

I will post the code and link to the data in a blog post later this week as it is a little too long for an issue! I would love to see this change in the main package so that I can now plot flows that span the globe from little old New Zealand! Thanks for writing such a wonderful package! :-) I had been looking for something like for a long time! 

![image](https://user-images.githubusercontent.com/3827179/166403713-8d6e670b-87c6-4b0a-825c-7f4a180cd5e2.png)

**Comment by schochastics** [comment]
I had the same problem for a long time and never bothered to fix it. Thanks @shriv for pointing it out. I implemented your fix now.
Will be in the next CRAN release but for now you need to install from github

**Comment by shriv** [comment]
That's amazing! Thanks a lot 😊😊
