### ISSUE TITLE
Edge bundling for parallel coordinates

### ISSUE THREAD

**Issue by jcalebsmith** [schochastics/edgebundle#13]
This is a great package. Have you considered adding something for parallel coordinates such as the algorithm described in the attached paper? I'm currently trying to figure out a way to approximate this result with your package. It would be great to have a function designed specifically for parallel coordinates though.

[Computer Graphics Forum - 2008 - Zhou - Visual Clustering in Parallel Coordinates.pdf](https://github.com/schochastics/edgebundle/files/9222689/Computer.Graphics.Forum.-.2008.-.Zhou.-.Visual.Clustering.in.Parallel.Coordinates.pdf)
![image](https://user-images.githubusercontent.com/48289425/181828576-5096c40c-7a28-425c-8edf-e3b928e1ed08.png)

**Comment by schochastics** [comment]
this looks great! I will put it on my todo list 
[Matlab code](https://www.cg.tuwien.ac.at/courses/Visualisierung2/HallOfFame/2016/MM/Homepage/index.html)
