### ISSUE TITLE
Move metrolayout to graphlayout

### ISSUE THREAD

**Issue by thomasp85** [schochastics/edgebundle#17]
Would it make sense to move the metro layout to the graphlayout package? This would make it easy to provide it in ggraph without porting it over since graphlayout is already a dependency. Or is there a dependency on this package for the layout that I'm not quite getting?

**Comment by schochastics** [comment]
Good idea. I was planning a little graphlayout work this week then I move it over.

**Comment by schochastics** [comment]
@thomasp85 started the process: https://github.com/schochastics/graphlayouts/pull/76
