### ISSUE TITLE
Add weight to edgebundle results 

### ISSUE THREAD

**Issue by xiaofanliang** [schochastics/edgebundle#5]
Hi David! 

I wonder if there is a way to add weights to the edge bundle results (e.g., fbundle, bundle etc.). The weights represent the volumes in the flow OD network, which is a common characteristic in network visualization. Ideally, I should be able to add weights to igraph object `g` (e.g., E(g)$weight = c(1,2,3)) and the return data frame from edgebundle will include an additional column that indicates weights by group. I assume that each group represents a line because the total number of groups and the total number of edges are consistent in your US flight example. Currently, I cannot figure out a way to match the bundled edges (or the group) to the original igraph object `g`, and thus cannot associate weights with the bundled edges. 

Can you help with a solution? 

Many thanks! 
Xiaofan

**Comment by schochastics** [comment]
the last column of the returned data frame ("group") contains the edge id. This can be used to match with the original igraph object.
At least I think so :)

**Comment by xiaofanliang** [comment]
Thanks David! Your solution works. The key is to match the group id with the edge pairs that are in the same order as the data that passed to the igraph object `g`. For example: 

```
g = graph_from_data_frame(OD, directed=TRUE)
node = data.frame(id = V(g)$name) 
xy = cbind(node$INTPTLON, node$INTPTLAT)

fbundle = edge_bundle_force(g,xy,compatibility_threshold = 0.9)
fbundle = fbundle %>% 
  left_join(OD %>% mutate(id = row_number()) %>% select(c(id, weight)), by=c('group' = 'id')) %>% 
  st_as_sf(coords=c('x', 'y'), crs=4326) %>%
  group_by(group) %>%
  summarise(weight=mean(weight), do_union=FALSE) %>% st_cast("LINESTRING")
```

This will return a nice line shapefile with flow weight.

**Comment by rfsaldanha** [comment]
That's great, thank you very much! A small contribution to plot the lines in order, based on the weight (smaller weights lines are plotted before, higher weights lines are plotted after, overlapping the smaller weights lines).

```
fbundle = edge_bundle_force(g,xy,compatibility_threshold = 0.9)
fbundle = fbundle %>% 
  left_join(OD %>% mutate(id = row_number()) %>% select(c(id, weight)), by=c('group' = 'id')) %>% 
  st_as_sf(coords=c('x', 'y'), crs=4326) %>%
  group_by(group) %>%
  summarise(weight=mean(weight), do_union=FALSE) %>%
  arrange(weight) %>%
  st_cast("LINESTRING")
```
