### ISSUE TITLE
Problems with hammer_bundle

### ISSUE THREAD

**Issue by fcorowe** [schochastics/edgebundle#9]
Hi,

First of all, thanks for the great package - stunning viz. 

I am trying to replicate the example [here](http://blog.schochastics.net/post/non-hierarchical-edge-bundling-in-r/), and I am hitting an error running this line:
`hbundle <- edge_bundle_hammer(g,xy,bw = 0.7,decay = 0.5)`

The error message is:
`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ImportError: hammer_bundle operation requires scikit-image. Ensure you install the dependency before applying bundling.`

I thought there was a compatibility issue with scikit-image so I installed a older version `scikit-image-0.17.2`. However, I keep getting the same issue. 

Any ideas on how to resolve the issue?

I am using: 
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16
```

**Comment by schochastics** [comment]
Thanks!
Did you try runing `install_bundle_py()`? This should install the dependencies correctly. If not let me know

**Comment by fcorowe** [comment]
yes, I did and it returns:

```
ERROR: Package 'xarray' requires a different Python: 3.6.10 not in '>=3.7'
Error: Error installing package(s): 'datashader'
```

**Comment by schochastics** [comment]
hmm ok I am out of ideas at the moment but I will investigate. Most likely rather a python version problem, but not sure
